articles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('new/', views.new),
    path('create/', views.create),
    path('<int:article_pk>/',views.detail),
    path('<int:article_pk>/edit/',views.edit),
    path('<int:article_pk>/update/',views.update),
    path('<int:article_pk>/delete/',views.delete),
]

previous/urls.py
from django.urls import path
from . import views

app_name = 'previous'

urlpatterns = [
    path('', views.index, name='index'),
    path('find/', views.find, name='find'),
]

reboot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('previous/', include('previous.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

previous/models.py
from django.db import models

# Create your models here.

class People(models.Model):
    name = models.CharField(max_length=5)
    job = models.CharField(max_length=10)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect(f'/articles/{article.pk}/')

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.GET.get('title')
    article.content = request.GET.get('content')
    article.save()
    return redirect(f'/articles/{article.pk}/')

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('/articles/')

previous/views.py
from django.shortcuts import render
from faker import Faker
from .models import People
from decouple import config
import requests
fake = Faker('ko_KR')

# Create your views here.
def index(request):
    return render(request, 'previous/index.html')

def find(request):
    name = request.POST.get('name')
    if not People.objects.filter(name=name).exists():
        job = fake.job()
        people = People(name = name, job = job)
        people.save()
    people = People.objects.filter(name=name)[0]
    
    # 직업 결과에 따라, giphy 요청
    job = people.job
    api_key = config('GIPHY_API_KEY')
    
    # 1. url 설정
    url = f'http://api.giphy.com/v1/gifs/search?api_key={api_key}&q={job}&lang=ko'
    
    # 2. 요청 보내기
    response = requests.get(url).json()
    
    # 3. 응답 결과에서 이미지 url 뽑기
    try:
        image_url = response.get('data')[0].get('images').get('original').get('url')
    except:
        image_url = None
    
    context = {
        'people' : people,
        'image_url' : image_url,
    }
    
    return render(request, 'previous/find.html', context)

articles/templates/articles/detail.html
{% extends 'articles/form.html' %}
{% block body %}
<h2> {{ article.title }} </h2>
<div>
  <p> 작성시간 : {{ article.created_at }} </p>
  <p> 수정시간 : {{ article.updated_at }} </p>
</div>
<hr>
<p>{{ article.content }}</p>
<a href="/articles/">게시판으로 돌아가기</a>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/form.html' %}
{% block body %}
<form action="/articles/{{ article.pk }}/update/" method="get">
  <label for="title">제목</label>
  <br>
  <textarea name="title" id="title" cols="80" rows="1">{{ article.title }}</textarea>
  <hr>
  <label for="content">내용</label>
  <br>
  <textarea name="content" id="content" cols="80" rows="60">{{ article.content }}</textarea>
  <input type="submit" value="제출">
</form>
{% endblock %}

articles/templates/articles/form.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>게시판</title>
</head>

<body>
    <h1>게시판</h1>
    {% block body %}
    {% endblock  %}
</body>

</html>

articles/templates/articles/index.html
{% extends 'articles/form.html' %}
{% block body %}
<a href="/articles/new/">글 작성하기</a>
<table>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">제 목</th>
      <th scope="col">작성일자</th>
      <th scope="col">수정일자</th>
      <th scope="col">비 고</th>
    </tr>
  </thead>
  {% for article in articles %}
  <tbody>
    <th>{{article.pk}}</th>
    <th><a href="/articles/{{ article.pk }}/">{{article.title}}</a></th>
    <th>{{article.created_at}}</th>
    <th>{{article.updated_at}}</th>
    <td>
      <a href="/articles/{{ article.pk }}/edit/">글 수정하기</a>
      <a href="/articles/{{ article.pk }}/delete/">글 삭제하기</a>
    </td>
  </tbody>
  {% endfor %}
</table>
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/form.html' %}
{% block body %}
<form action="/articles/create" method="get">
  <label for="title">제목</label>
  <br>
  <input type="text" name="title" id="title">
  <hr>
  <label for="content">내용</label>
  <br>
  <textarea name="content" id="content" cols="100" rows="60"></textarea>
  <input type="submit" value="제출">
</form>
{% endblock %}

previous/templates/previous/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>당신의 전생은?</title>
</head>

<body>
  {% block body %}
  {% endblock %}
</body>

</html>

previous/templates/previous/find.html
{% extends 'previous/base.html' %}
{% block body %}
  <p>{{ people.name }}님은 전생에</p>
  <p>{{ people.job }}이였습니다!!</p>
  <img src=" {{ image_url }}" alt="job_image">
  <hr>
  <a href="{% url 'previous:index' %}">다른 사람 전생 찾기!</a>

{% endblock %}

previous/templates/previous/index.html
{% extends 'previous/base.html' %}

{% block body %}
<form action="{% url 'previous:find' %}" method="POST">
  {% csrf_token %}
  <label for="name">이름을 입력해 주세요</label>
  <hr>
  <input type="text" name="name" id="name">
  <br>
  <input type="submit" value="입력!!">
</form>
{% endblock %}